FROM ubuntu

RUN apt-get update && apt-get install -y nginx && apt-get -y install php7.0-fpm && sed -i 's@listen = /run/php/php7.0-fpm.sock@listen = 9000@' /etc/php/7.0/fpm/pool.d/www.conf && echo "<?php" >>/var/www/html/index.php && echo "phpinfo();" >>/var/www/html/index.php && echo "?>" >>/var/www/html/index.php
COPY default /etc/nginx/sites-enabled/default
CMD service nginx start && service php7.0-fpm start && bash
