FROM ubuntu
RUN apt-get update && apt-get -y install apt-utils && DEBIAN_FRONTEND=noninteractive apt-get -y install mysql-server && apt-get install -y net-tools && ip="$(ifconfig | grep -A 1 'eth0' | tail -1 | cut -d ':' -f 2 | cut -d ' ' -f 1)" && service mysql start && mysql -uroot -e "create database wordpress" && mysql -uroot -e "CREATE USER 'wordpressuser'@'%' IDENTIFIED BY 'password';" && mysql -uroot -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpressuser'@'%';" && mysql -uroot -e "FLUSH PRIVILEGES;" && sed -i 's/= 127.0.0.1/= '"$ip"'/' /etc/mysql/mysql.conf.d/mysqld.cnf 
CMD service mysql start && tail -f /var/log/mysql/error.log

